version: '3.7'
services:

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: "148793515739.dkr.ecr.us-west-2.amazonaws.com/app:1"
    ports:
      - 80:80
      - 443:443
    # command: /bin/bash scripts/dev-init